### ISSUE TITLE
Missing files.

### ISSUE THREAD

**Issue by oblogic7** [stanford-gfx/Horus#1]
I am very close to having this running.  However, it appears that the `js/lib` and `css/lib` folders are missing from the repo.

**Comment by jleppert** [comment]
+1. I actually got it to run by manually finding the missing dependencies. However, there are numerous issues with p5.js. Wondering if you could commit or give us the versions of those files?

**Comment by mikeroberts3000** [comment]
Hi friends, sorry about the super delayed reply here. I just uploaded the relevant files to this repo, fixed some other stuff, and cleaned up the install instructions doc. I hope that helps :)

@oblogic7 and @jleppert
