### ISSUE TITLE
"We don't have a starting altitude, we cannot fly!"

### ISSUE THREAD

**Issue by gary-w-johnson** [stanford-gfx/Horus#4]
Have reinstalled on a mac pro per installation instructions and everything seems to be working ok.

When I press the "Start Flight" Button I is get the message: "We don't have a starting altitude, we cannot fly!"

How and where do you enter the correct starting altitude?

Also did you have this working and flying using a 3DR Solo?

**Comment by mikeroberts3000** [comment]
Hi Gary, we did have the app working and flying with a 3DR Solo. But I think there needs to be another Python script running in the background on your laptop (responsible for communicating with the drone) that may not have made it into the public repository. I'll look into this.

CC'ing @njoubert in case he has anything to add.

**Comment by gary-w-johnson** [comment]
Hi Mike, thanks for checking for missing script.  Would like to try this with my Solo.

**Comment by njoubert** [comment]
hi guys!

yea, we have the infrastructure but not all of that has been pushed to
public yet.

i just got out of surgery yesterday and im hopped up on a lot of
painkillers, so if you give me a few days to come back to normal, ill take
a look and figure it out!


-Niels

**Comment by gary-w-johnson** [comment]
No rush, take it easy and get well first

**Comment by njoubert** [comment]
Hi gary! Are you still trying to get this working?

**Comment by gary-w-johnson** [comment]
Mike, yes,slow but sure.  Seems we have lost Google Earth API but working
on using Google Map as a replacement.

If you can get the missing infrastructure posted will still be a big help
in the process.

Gary

**Comment by mikeroberts3000** [comment]
The Google Earth web plugin is finally deprecated, and Horus is currently not functional. So I'm closing this issue.
